Added round edges to "WHAT WE OFFER" section #204
The-Shivam-garg/BigB-E-learn-Websit-e pull request #207
Opened 2022-03-19 17:32 UTC by The-Arshad-Khan

## 🛠️ Fixes Issue

Closes #

## 👨‍💻 Changes proposed
Added Round Edges To "WHAT WE OFFER" SECTION.

## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/82707877/159131869-9b2d3678-239d-4108-9503-f495bb3c3fab.png)

2022-03-19 18:18 UTC, sakshamgurbhele requested changes
Hey @The-Arshad-Khan, Can you delay the transition for 1-2 seconds, it will feel better I think.

2022-03-19 18:18 UTC, sakshamgurbhele commented on css/main.css
> +  -o-border-radius: 20px;
lgtm

2022-03-20 10:16 UTC, The-Arshad-Khan commented on css/main.css
> +  -o-border-radius: 20px;
@sakshamgurbhele On it;

2022-03-20 10:19 UTC, The-Arshad-Khan commented on css/main.css
> +  -o-border-radius: 20px;
and Done!

2022-03-20 17:28 UTC, The-Arshad-Khan commented
@sakshamgurbhele Kindly merge my PR!

2022-03-21 19:04 UTC, sakshamgurbhele commented
@The-Arshad-Khan Thank You for Contributing, Merging it 🚀

2022-03-21 19:05 UTC, merged

2022-03-21 19:05 UTC, sakshamgurbhele reviewed
cool 👍🏼