Improved navbar
The-Shivam-garg/BigB-E-learn-Websit-e pull request #284
Opened 2022-04-07 06:12 UTC by Areebah03

*Fixed #274 

## 🛠️ Fixes Issue

Fixes #274 

## 👨‍💻 Changes proposed

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

I have improved the navbar of the website by changing fonts, colors and hover effects.

## 📷 Screenshots

| Before | After |
| --- | ---- |
| ![Capture](https://user-images.githubusercontent.com/85051124/162131954-796e7373-d480-45ce-8c3d-df9a512c04d2.PNG) | ![ss1](https://user-images.githubusercontent.com/85051124/162132004-4c434be3-7e47-4310-8077-20ad282b151b.PNG) |

2022-04-07 07:04 UTC, sakshamgurbhele requested changes

2022-04-07 07:04 UTC, sakshamgurbhele commented on style.css
> +}
can you make the sides circular? not everyone will like this leafy / edged design tbh.

2022-04-07 07:38 UTC, Areebah03 commented
@sakshamgurbhele I have made the sides circular. Kindly view it.

2022-04-08 11:18 UTC, sakshamgurbhele approved these changes

2022-04-08 11:18 UTC, sakshamgurbhele commented on style.css
> +   border-radius: 50px 50px 50px 50px;
👍🏼

2022-04-08 11:18 UTC, sakshamgurbhele commented
@Areebah03 Please Resolve the conflicts, so that we can merge it 🚀

2022-04-08 11:32 UTC, Areebah03 commented
@sakshamgurbhele I have resolve the merge conflicts.

2022-04-11 18:12 UTC, merged