Made some changes in Navbar and Contact section
The-Shivam-garg/BigB-E-learn-Websit-e pull request #443
Opened 2022-10-04 06:02 UTC by Rashmisingh-18

## 🛠️ Fixes Issue 

Closes #401 

## 👨‍💻 Changes proposed

Changed Navbar on hovering 
In the Contact section, made some changes in the view of the main section so that it can cover the background.

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## 📄 Note to reviewers

## 📷 Screenshots
![Feature and 7 more pages - Personal - Microsoft​ Edge 04-10-2022 11 30 33 AM](https://user-images.githubusercontent.com/90052358/193745829-46147644-c91b-46a9-a772-8062b0932a2e.png)
![Feature and 7 more pages - Personal - Microsoft​ Edge 04-10-2022 11 30 21 AM](https://user-images.githubusercontent.com/90052358/193745842-aab3918f-a5fe-4630-bbe3-247e79d39d0a.png)

2022-10-04 16:32 UTC, The-Shivam-garg requested changes
hey @Rashmisingh-18 , i am convinced with the changes you made in the course section but not with the features one.So please create another pr with only those changes that you made in course section.

2022-10-04 16:50 UTC, Rashmisingh-18 commented
In features, added that background color in the CSS file, and the navbar bug was also in that one, which I fixed.

2022-10-05 17:39 UTC, The-Shivam-garg commented
> In features, added that background color in the CSS file, and the navbar bug was also in that one, which I fixed.

i'm saying just make the feature background color as it was before , and create a pr after doing so  along with the improvements of navbar bug.

2022-10-12 15:33 UTC, The-Shivam-garg approved these changes

2022-10-12 15:34 UTC, merged